/**
 * Everything that has to exist before `next build` runs.
 *
 * Wired as npm's `prebuild`, so it runs on `npm run build` without anyone
 * having to remember it — including in CI, and including on Cloudflare's build
 * runner, which is the case that actually matters.
 */

import { readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";

/**
 * Translate config/redirects.json into Cloudflare's `_redirects` format.
 *
 * `next.config.ts` cannot own these: Next ignores `redirects()` under
 * `output: "export"`, so declaring them there would be dead code that looks
 * live. See config/redirects.README.md for the full reasoning and for what to
 * do if this site ever moves off Cloudflare.
 *
 * Cloudflare reads the file top to bottom and stops at the first match, so the
 * order in the JSON is significant — the specific Priora rule has to precede
 * the `:slug` wildcard or it can never be reached.
 */
async function writeRedirects() {
  const rules = JSON.parse(await readFile("config/redirects.json", "utf8"));

  const lines = [
    "# Generated by scripts/prebuild.mjs from config/redirects.json.",
    "# Do not edit by hand: the next build overwrites it.",
    "",
    ...rules.map(({ from, to }) => `${from}  ${to}  301`),
    ""
  ];

  await writeFile("public/_redirects", lines.join("\n"));
  console.log(`redirects: wrote ${rules.length} rules to public/_redirects`);
}

function buildImages() {
  // Its own process because sharp is a native addon, and a failure to load it
  // should name itself rather than surfacing as an opaque prebuild crash.
  const result = spawnSync(process.execPath, ["scripts/build-images.mjs"], {
    stdio: "inherit"
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

await writeRedirects();
buildImages();
