/**
 * Everything that has to exist before `next build` runs.
 *
 * Wired as npm's `prebuild`, so it runs on `npm run build` without anyone
 * having to remember it — including in CI, and including on Cloudflare's build
 * runner, which is the case that actually matters.
 */

import { readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";

/**
 * Translate config/redirects.json into Cloudflare's `_redirects` format.
 *
 * `next.config.ts` cannot own these: Next ignores `redirects()` under
 * `output: "export"`, so declaring them there would be dead code that looks
 * live. See config/redirects.README.md for the full reasoning and for what to
 * do if this site ever moves off Cloudflare.
 *
 * Cloudflare reads the file top to bottom and stops at the first match, so the
 * order in the JSON is significant — the specific Priora rule has to precede
 * the `:slug` wildcard or it can never be reached.
 */
async function writeRedirects() {
  const rules = JSON.parse(await readFile("config/redirects.json", "utf8"));

  const lines = [
    "# Generated by scripts/prebuild.mjs from config/redirects.json.",
    "# Do not edit by hand: the next build overwrites it.",
    "",
    ...rules.map(({ from, to }) => `${from}  ${to}  301`),
    ""
  ];

  await writeFile("public/_redirects", lines.join("\n"));
  console.log(`redirects: wrote ${rules.length} rules to public/_redirects`);
}

/**
 * Write `public/_headers`, which Cloudflare's static host applies at the edge.
 *
 * Two things are wrong without it, both found by checking the deployed site
 * rather than the build:
 *
 * 1. `/opengraph-image` is served with **no Content-Type at all**. Next's
 *    metadata route emits the file with no extension, and Cloudflare infers the
 *    type from the extension, so there is nothing to infer from. Every social
 *    scraper that fetches that URL gets a typeless body and declines to render
 *    a preview — which matters, because sharing this link on LinkedIn is most
 *    of what it is for.
 *
 * 2. Everything is served `max-age=0, must-revalidate`, including the
 *    content-hashed chunks under `/_next/static`. Those filenames change
 *    whenever their contents do, so revalidating them is pure round-trip cost
 *    on every navigation.
 *
 * Note the asymmetry in the two cache rules. `/_next/static` is `immutable`
 * because Next puts a content hash in the filename. `/assets` is not hashed —
 * replacing the photograph reuses `portrait-840.avif` — so it gets a week with
 * `stale-while-revalidate` instead. Marking those immutable would strand
 * readers on an old portrait for a year.
 *
 * HTML deliberately keeps `must-revalidate`, so a deploy is visible at once.
 */
async function writeHeaders() {
  const lines = [
    "# Generated by scripts/prebuild.mjs. Do not edit by hand.",
    "",
    "# Next's metadata route emits this with no file extension, so Cloudflare",
    "# has nothing to infer a type from and sends it untyped.",
    "/opengraph-image",
    "  Content-Type: image/png",
    "  Cache-Control: public, max-age=3600",
    "",
    "# Content-hashed by Next: a change to the bytes changes the filename.",
    "/_next/static/*",
    "  Cache-Control: public, max-age=31536000, immutable",
    "",
    "# Not hashed. A week, then revalidate in the background.",
    "/assets/*",
    "  Cache-Control: public, max-age=604800, stale-while-revalidate=86400",
    ""
  ];

  await writeFile("public/_headers", lines.join("\n"));
  console.log("headers: wrote public/_headers");
}

function buildImages() {
  // Its own process because sharp is a native addon, and a failure to load it
  // should name itself rather than surfacing as an opaque prebuild crash.
  const result = spawnSync(process.execPath, ["scripts/build-images.mjs"], {
    stdio: "inherit"
  });
  if (result.status !== 0) process.exit(result.status ?? 1);
}

await writeRedirects();
await writeHeaders();
buildImages();
